In [1]:
#first importing
import numpy as np

In [2]:
#Creating an array
arr = np.arange(0,5)

In [21]:
#this is index based operations. [0] + [0], [1] + [1], and so on
arr + arr, arr-arr, arr*arr, arr/arr, 1/arr, arr ** 2, 
#First error: happens because 0/0 is undefined, and so it is replaced with nan
#Second error: happens because 1/0 is infinitly many numbers, and so it is replaced with inf.

D:\Program Files (x86)\Anaconda\envs\pyt4\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
D:\Program Files (x86)\Anaconda\envs\pyt4\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


(array([0, 2, 4, 6, 8]),
 array([0, 0, 0, 0, 0]),
 array([ 0,  1,  4,  9, 16]),
 array([nan,  1.,  1.,  1.,  1.]),
 array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ]),
 array([ 0,  1,  4,  9, 16], dtype=int32),
 array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ]),
 4,
 0)

In [24]:
#There are also special functions in NumPy making data manipulation easier and more efficient.
np.sqrt(arr), np.max(arr), np.min(arr), np.exp(arr), np.log(arr), np.deg2rad(arr), np.rad2deg(arr)
#Error because of log making infinity when doing log 0

D:\Program Files (x86)\Anaconda\envs\pyt4\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


(array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ]),
 4,
 0,
 array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003]),
 array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436]),
 array([0.        , 0.01745329, 0.03490659, 0.05235988, 0.06981317]),
 array([  0.        ,  57.29577951, 114.59155903, 171.88733854,
        229.18311805]))