In [1]:
#Lets import numpy
import numpy as np

In [2]:
#Lets create a python list
my_list = [-1,0,1]
my_list, type(my_list)

([-1, 0, 1], list)

In [3]:
my_array = np.array(my_list)
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [4]:
#Lets create and cast a list of lists to generate a 2D array
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
#Converting list to Matrix
matrix_one = np.array(my_matrix)
matrix_one
#Can be done with tuples as well

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#arange. Similar to Range in python, but output becomes numpy array
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#Step size can be used, and specific datatype using dtype
np.arange(0,11,2, dtype=float)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [8]:
#kinspace. Returns evenly spaced numbers over a specified interval. 
np.linspace(1,15,15)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [9]:
#Can show step size as well. Use retstep.
np.linspace(5,15,9, retstep=True)

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

## Don't Confuse!
  * <b>`arange()` takes 3rd argument as step size.<b><br>
  * <b>`linspace()` take 3rd argument as no of point we want.<b>

In [10]:
#Using Zeros. 1D element:
np.zeros(3)

array([0., 0., 0.])

In [11]:
#Using Zeros. 2D Element:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
#ones() can create a matrix of ones. Same use as zeros
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
#eye can create identity matrixes
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random Library in Numpy

In [15]:
#rand can create random numbers in a 1d or 2d array
np.random.rand(3)

array([0.37258988, 0.03356958, 0.37652452])

In [16]:
np.random.rand(4,5)

array([[0.85626448, 0.91349086, 0.29580496, 0.87304832, 0.53722378],
       [0.69460165, 0.77677264, 0.24393638, 0.81072017, 0.37771446],
       [0.75781317, 0.51550729, 0.37744421, 0.58775664, 0.70710899],
       [0.82267683, 0.5308407 , 0.21309226, 0.75011321, 0.2733956 ]])

In [17]:
#randn can use gaussian distribution creating a sample
np.random.randn(3)

array([ 0.01110211,  0.30260127, -0.67621836])

In [18]:
np.random.randn(4,5)

array([[ 0.06530787, -0.08739666, -0.96210694,  0.20352573,  0.17648933],
       [ 0.88678447,  2.30055548, -0.24156077, -1.36123776, -1.31328037],
       [-0.73867309,  0.93890047,  0.09284917, -0.57765661,  1.68025967],
       [ 1.31628579,  2.49615759,  1.26901551, -0.87055767,  0.01646441]])

In [19]:
#randint returns a random number between given bounds, second being exclusive
np.random.randint(1,100)

40

## Methods like
 * reshape(), max(), min(), argmax(), argmin()

In [20]:
# lets create 2 arrays using arange() and randint()
array_arange = np.arange(16) #Creates a 0 to 15 array. 
array_ranint = np.random.randint(0,100,10) #Create an array of size 10 with random numbers from 1 to 100

In [21]:
array_arange = array_arange.reshape(4,4) # makes the 1d array into a 2d array. Dimentions must be factors of array size

In [22]:
#shows our random numbers from the ranint created array
array_ranint

array([35, 31, 66, 95,  4, 13, 33, 94, 15, 98])

In [23]:
#finds the max number of the random array
array_ranint.max()

98

In [24]:
#finds the minumum number of the random array
array_ranint.min()

4

In [25]:
#Finds the index location of the max number in given list
array_ranint.argmax()

9

In [26]:
#finds index location of minimum number in given list
array_ranint.argmin()

4

## Attributes
* size, shape, dtype

In [27]:
#finding the shape of the array given
array_arange.shape

(4, 4)

In [28]:
array_arange.size

16

In [29]:
array_arange.dtype

dtype('int32')