In [1]:
#Importing Numpy
import numpy as np

In [2]:
#Create a simple array using list
array_id = np.array([-10,-2,0,2,17,106,200])

In [3]:
#indexing works the same as normal arrays
array_id[0]

-10

In [4]:
#Can grab multiple values
array_id[0:3]

array([-10,  -2,   0])

In [9]:
#grabbing all elements from an index. Can decide if its right or left. This is called Slicing
array_id[:2], array_id[2:]

(array([-10,  -2]), array([  0,   2,  17, 106, 200]))

In [10]:
#you can assign values to arrays
array_id[0] = -106

In [11]:
#It replaces the first index
array_id

array([-106,   -2,    0,    2,   17,  106,  200])

## Indexing

In [14]:
#create a 2d array
array_2d = np.arange(24)
array_2d = array_2d.reshape(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
#accessing elements requires [row, column]
array_2d[0,3]

3

In [53]:
#you can also get a complete row
array_2d[2], array_2d[-4]

(array([ 8,  9, 10, 11]), array([ 8,  9, 10, 11]))

In [27]:
#2d array slicing. This grabs the first 2 by 2 matrix, starting from row0 to row 2, column 0 to column 2
array_2d[:3,:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [59]:
#You can get an inner slice as well
array_2d[0:5,0:1]

array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16]])